# Generated by Django 2.0.7 on 2018-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_datospersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonal',
            name='documento_identidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datospersonal',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
