# Generated by Django 2.0.7 on 2018-07-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20180724_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonal',
            name='foto',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
