# Generated by Django 2.0.7 on 2018-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20180724_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonal',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', 'Gerente'), ('2', 'Tesorero'), ('3', 'Cliente'), ('4', 'Conductor')], default=3, max_length=1),
        ),
    ]
