# Generated by Django 2.0.7 on 2018-08-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_tipovehiculo_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
